Add checks for existing keystore and truststore files when creating Kafka client
exasol/cloud-storage-etl-udfs pull request #92
Opened 2020-09-03 06:31 UTC by jwarlander

To avoid getting a confusing error deeper in the stack that surfaces to the Exasol query result, check to make sure that the keystore and truststore files actually exist while validating the Kafka client. This allows us to show a more understandable message that can be acted on directly.

2020-09-03 07:00 UTC, morazow requested changes
One minor request, and then good to merge!

2020-09-03 07:00 UTC, morazow commented on src/main/scala/com/exasol/cloudetl/kafka/KafkaConsumerProperties.scala
> +    }
:+1: 

Only specifying the location in connection object may not help :) The file should exist in BucketFS path.

2020-09-03 07:00 UTC, morazow commented on src/main/scala/com/exasol/cloudetl/kafka/KafkaConsumerProperties.scala
> +    import java.nio.file.{Files, Paths}
Could you please move this to the imports at the beginning of the file?

2020-09-03 13:10 UTC, merged

2020-09-03 13:10 UTC, morazow commented
Great! 
Thanks sending these changes @jwarlander!

2020-09-03 14:19 UTC, jwarlander commented
Thanks, I was looking at an out-of-date version of this page just now so I re-sent a review request, but it seems safe to ignore now ;)

2020-09-17 05:13 UTC, morazow commented
Ahh yes, that happens to us on daily basis :)